include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    avoid_print: true
    avoid_unused_constructor_parameters: true
    camel_case_types: true
    cancel_subscriptions: true
    close_sinks: true
    implementation_imports: true
    library_names: true
    library_prefixes: true
    package_names: true
    package_prefixed_library_names: true
    prefer_contains: true
    prefer_initializing_formals: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_typing_uninitialized_variables: true
    slash_for_doc_comments: true
    test_types_in_equals: true
    type_init_formals: true
    unnecessary_brace_in_string_interps: true
    unnecessary_getters_setters: true
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_statements: true
    unrelated_type_equality_checks: true
    use_rethrow_when_possible: true
    valid_regexps: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "lib/generated/**"
  errors:
    invalid_annotation_target: ignore
